services:
  server:
    build:
      context: .
      dockerfile: apps/servers/express/Dockerfile
    container_name: express-server
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - root_node_modules:/app/node_modules
      - server_node_modules:/app/apps/servers/express/node_modules
    stdin_open: true
    tty: true

  client:
    build:
      context: .
      dockerfile: apps/clients/web/react-lab/Dockerfile
    container_name: react-lab-client
    ports:
      - "5173:5173" # vite react
      - "6006:6006" # storybook
    volumes:
      - .:/app
      - root_node_modules:/app/node_modules
      - client_node_modules:/app/apps/clients/web/react-lab/node_modules
    stdin_open: true
    tty: true

volumes:
  root_node_modules:
  server_node_modules:
  client_node_modules: